// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
