// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetHttpPort() {
  return window['go']['main']['App']['GetHttpPort']();
}

export function GetMusicFilePath(arg1) {
  return window['go']['main']['App']['GetMusicFilePath'](arg1);
}

export function GetPeerAddress() {
  return window['go']['main']['App']['GetPeerAddress']();
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function SearchSongs(arg1) {
  return window['go']['main']['App']['SearchSongs'](arg1);
}

export function SelectFileAndUpload() {
  return window['go']['main']['App']['SelectFileAndUpload']();
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
