// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {__} from '../models';

export function DownloadFile(arg1:string):Promise<string>;

export function EnableSeeding(arg1:string):Promise<void>;

export function EventEmitter(arg1:string,arg2:any):Promise<void>;

export function GetContributorStatus():Promise<boolean>;

export function GetHttpPort():Promise<string>;

export function GetLibraryTorrents():Promise<Array<client.TorrentInfo>>;

export function GetMusicFilePath(arg1:string):Promise<string>;

export function GetPeerAddress():Promise<string>;

export function GetTorrents():Promise<Array<client.TorrentInfo>>;

export function SearchSongs(arg1:string):Promise<Array<__.SongInfo>>;

export function SelectFileAndUpload():Promise<string>;

export function StopSeeding(arg1:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<string>;
