// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: napster.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CentralServer_SearchFile_FullMethodName          = "/napster.CentralServer/SearchFile"
	CentralServer_UploadFile_FullMethodName          = "/napster.CentralServer/UploadFile"
	CentralServer_GetTorrent_FullMethodName          = "/napster.CentralServer/GetTorrent"
	CentralServer_EnableSeeding_FullMethodName       = "/napster.CentralServer/EnableSeeding"
	CentralServer_StopSeeding_FullMethodName         = "/napster.CentralServer/StopSeeding"
	CentralServer_HealthCheck_FullMethodName         = "/napster.CentralServer/HealthCheck"
	CentralServer_HealthCheckServer_FullMethodName   = "/napster.CentralServer/HealthCheckServer"
	CentralServer_RegisterContributor_FullMethodName = "/napster.CentralServer/RegisterContributor"
)

// CentralServerClient is the client API for CentralServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CentralServerClient interface {
	// rpc RegisterPeer(RegisterRequest) returns (RegisterResponse);
	SearchFile(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// rpc GenerateTorrent(TorrentRequest) returns (TorrentResponse);
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error)
	GetTorrent(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
	EnableSeeding(ctx context.Context, in *SeedingRequest, opts ...grpc.CallOption) (*GenResponse, error)
	StopSeeding(ctx context.Context, in *SeedingRequest, opts ...grpc.CallOption) (*GenResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	HealthCheckServer(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	RegisterContributor(ctx context.Context, in *ContributorRequest, opts ...grpc.CallOption) (*GenResponse, error)
}

type centralServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralServerClient(cc grpc.ClientConnInterface) CentralServerClient {
	return &centralServerClient{cc}
}

func (c *centralServerClient) SearchFile(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, CentralServer_SearchFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CentralServer_ServiceDesc.Streams[0], CentralServer_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CentralServer_UploadFileClient = grpc.ClientStreamingClient[FileChunk, UploadResponse]

func (c *centralServerClient) GetTorrent(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, CentralServer_GetTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) EnableSeeding(ctx context.Context, in *SeedingRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, CentralServer_EnableSeeding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) StopSeeding(ctx context.Context, in *SeedingRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, CentralServer_StopSeeding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CentralServer_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) HealthCheckServer(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CentralServer_HealthCheckServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServerClient) RegisterContributor(ctx context.Context, in *ContributorRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, CentralServer_RegisterContributor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralServerServer is the server API for CentralServer service.
// All implementations must embed UnimplementedCentralServerServer
// for forward compatibility.
type CentralServerServer interface {
	// rpc RegisterPeer(RegisterRequest) returns (RegisterResponse);
	SearchFile(context.Context, *SearchRequest) (*SearchResponse, error)
	// rpc GenerateTorrent(TorrentRequest) returns (TorrentResponse);
	UploadFile(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error
	GetTorrent(context.Context, *SearchRequest) (*TorrentResponse, error)
	EnableSeeding(context.Context, *SeedingRequest) (*GenResponse, error)
	StopSeeding(context.Context, *SeedingRequest) (*GenResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	HealthCheckServer(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	RegisterContributor(context.Context, *ContributorRequest) (*GenResponse, error)
	mustEmbedUnimplementedCentralServerServer()
}

// UnimplementedCentralServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCentralServerServer struct{}

func (UnimplementedCentralServerServer) SearchFile(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFile not implemented")
}
func (UnimplementedCentralServerServer) UploadFile(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedCentralServerServer) GetTorrent(context.Context, *SearchRequest) (*TorrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTorrent not implemented")
}
func (UnimplementedCentralServerServer) EnableSeeding(context.Context, *SeedingRequest) (*GenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableSeeding not implemented")
}
func (UnimplementedCentralServerServer) StopSeeding(context.Context, *SeedingRequest) (*GenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSeeding not implemented")
}
func (UnimplementedCentralServerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCentralServerServer) HealthCheckServer(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheckServer not implemented")
}
func (UnimplementedCentralServerServer) RegisterContributor(context.Context, *ContributorRequest) (*GenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterContributor not implemented")
}
func (UnimplementedCentralServerServer) mustEmbedUnimplementedCentralServerServer() {}
func (UnimplementedCentralServerServer) testEmbeddedByValue()                       {}

// UnsafeCentralServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentralServerServer will
// result in compilation errors.
type UnsafeCentralServerServer interface {
	mustEmbedUnimplementedCentralServerServer()
}

func RegisterCentralServerServer(s grpc.ServiceRegistrar, srv CentralServerServer) {
	// If the following call pancis, it indicates UnimplementedCentralServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CentralServer_ServiceDesc, srv)
}

func _CentralServer_SearchFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).SearchFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_SearchFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).SearchFile(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CentralServerServer).UploadFile(&grpc.GenericServerStream[FileChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CentralServer_UploadFileServer = grpc.ClientStreamingServer[FileChunk, UploadResponse]

func _CentralServer_GetTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).GetTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_GetTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).GetTorrent(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_EnableSeeding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).EnableSeeding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_EnableSeeding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).EnableSeeding(ctx, req.(*SeedingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_StopSeeding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).StopSeeding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_StopSeeding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).StopSeeding(ctx, req.(*SeedingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_HealthCheckServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).HealthCheckServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_HealthCheckServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).HealthCheckServer(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralServer_RegisterContributor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContributorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServerServer).RegisterContributor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralServer_RegisterContributor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServerServer).RegisterContributor(ctx, req.(*ContributorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CentralServer_ServiceDesc is the grpc.ServiceDesc for CentralServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentralServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "napster.CentralServer",
	HandlerType: (*CentralServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchFile",
			Handler:    _CentralServer_SearchFile_Handler,
		},
		{
			MethodName: "GetTorrent",
			Handler:    _CentralServer_GetTorrent_Handler,
		},
		{
			MethodName: "EnableSeeding",
			Handler:    _CentralServer_EnableSeeding_Handler,
		},
		{
			MethodName: "StopSeeding",
			Handler:    _CentralServer_StopSeeding_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CentralServer_HealthCheck_Handler,
		},
		{
			MethodName: "HealthCheckServer",
			Handler:    _CentralServer_HealthCheckServer_Handler,
		},
		{
			MethodName: "RegisterContributor",
			Handler:    _CentralServer_RegisterContributor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _CentralServer_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "napster.proto",
}

const (
	PeerService_RequestChunk_FullMethodName     = "/napster.PeerService/RequestChunk"
	PeerService_HealthCheck_FullMethodName      = "/napster.PeerService/HealthCheck"
	PeerService_DownloadThisFile_FullMethodName = "/napster.PeerService/DownloadThisFile"
)

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerServiceClient interface {
	RequestChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	DownloadThisFile(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*GenResponse, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) RequestChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkResponse)
	err := c.cc.Invoke(ctx, PeerService_RequestChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PeerService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) DownloadThisFile(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, PeerService_DownloadThisFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility.
type PeerServiceServer interface {
	RequestChunk(context.Context, *ChunkRequest) (*ChunkResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	DownloadThisFile(context.Context, *SearchRequest) (*GenResponse, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerServiceServer struct{}

func (UnimplementedPeerServiceServer) RequestChunk(context.Context, *ChunkRequest) (*ChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestChunk not implemented")
}
func (UnimplementedPeerServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPeerServiceServer) DownloadThisFile(context.Context, *SearchRequest) (*GenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadThisFile not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}
func (UnimplementedPeerServiceServer) testEmbeddedByValue()                     {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerService_ServiceDesc, srv)
}

func _PeerService_RequestChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RequestChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_RequestChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RequestChunk(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_DownloadThisFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).DownloadThisFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_DownloadThisFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).DownloadThisFile(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerService_ServiceDesc is the grpc.ServiceDesc for PeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "napster.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestChunk",
			Handler:    _PeerService_RequestChunk_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PeerService_HealthCheck_Handler,
		},
		{
			MethodName: "DownloadThisFile",
			Handler:    _PeerService_DownloadThisFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "napster.proto",
}
